sudo: required

services:
  - docker 

before_install: 
  - docker build -t jonny5592/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jonny5592/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-879238464235"
  bucket_path: "Docker React"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"